name: Step 3 # Last step of the exercise

on:
  workflow_dispatch:
  # Common event triggers: pull_request, push, issues, issue_comment (feel free to experiment)
  # Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  # Example:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.6.0

  post_review_content:
    name: Post review content
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}
      ISSUE_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.6.0

      - name: Create comment - step finished - final review next
        uses: GrantBirki/comment@v2.1.1
        with:
          file: exercise-toolkit/markdown-templates/step-feedback/lesson-review.md
          issue-number: ${{ env.ISSUE_NUMBER }}
          repository: ${{ env.ISSUE_REPOSITORY }}

      - name: Create comment - add review content
        uses: GrantBirki/comment@v2.1.1
        with:
          file: ${{ env.REVIEW_FILE }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          repository: ${{ env.ISSUE_REPOSITORY }}

      - name: Disable current workflow
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.6.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      exercise-title: "(replace-me: Exercise title)"
